CREATE TABLE IF NOT EXISTS product_images (
    id BIGSERIAL PRIMARY KEY,
    url VARCHAR(512) NOT NULL,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    is_cover BOOLEAN NOT NULL DEFAULT FALSE
);